# Generated by Django 5.2.6 on 2025-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_explanation_quiz_is_active_quizmember_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='quizmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizresults',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='code',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
