# Generated by Django 5.2.6 on 2025-12-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_answer_explanation_remove_quiz_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
