"""Add image_url field to Question model

Generated by assistant.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizsession_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
